/*
 * RenderResourceType.h
 *
 *  Created on: Feb 21, 2019
 *      Author: rookyma
 */

#ifndef SOURCE_CORE_RENDER_RENDERRESOURCETYPE_H_
#define SOURCE_CORE_RENDER_RENDERRESOURCETYPE_H_

#include <cstdint>

namespace Render
{

enum class ResourceType : uint32_t
{
	RESOURCE_TYPE_COMMON,
	RESOURCE_TYPE_BUFFER,
	RESOURCE_TYPE_TEXTURE,
	RESOURCE_TYPE_UNIFORM,
	RESOURCE_TYPE_SAMPLER,
	RESOURCE_TYPE_TARGET,
	RESOURCE_TYPE_UNKNOWN = ~0U
};

}



#endif /* SOURCE_CORE_RENDER_RENDERRESOURCETYPE_H_ */
