/*
 * RenderTypes.h
 *
 *  Created on: Jan 28, 2019
 *      Author: rookyma
 */

#ifndef SOURCE_CORE_RENDER_RENDERTYPES_H_
#define SOURCE_CORE_RENDER_RENDERTYPES_H_

#include <cstdint>

namespace Render
{
	enum class ImageType : uint32_t
	{
		IMAGE_TYPE_1D,
		IMAGE_TYPE_2D,
		IMAGE_TYPE_3D,
		IMAGE_TYPE_CUBE,
		IMAGE_TYPE_1D_ARRAY,
		IMAGE_TYPE_2D_ARRAY,
		IMAGE_TYPE_CUBE_ARRAY,
		IMAGE_TYPE_UNKNOWN = ~0u
	};

	enum class IndexType : uint32_t
	{
		INDEX_TYPE_U16,
		INDEX_TYPE_U32,
		INDEX_TYPE_UNKNOWN = ~0u
	};

	enum class BufferUsage : uint32_t
	{
		BUFFER_USAGE_INDEX,
		BUFFER_USAGE_VERTEX,
		BUFFER_USAGE_UNIFORM,
		BUFFER_USAGE_STORAGE,
		BUFFER_USAGE_INDIRECT,
		BUFFER_USAGE_UNIFORM_TEXEL,
		BUFFER_USAGE_STORAGE_TEXEL,
		BUFFER_USAGE_UNKNOWN = ~0u
	};
}

#endif /* SOURCE_CORE_RENDER_RENDERTYPES_H_ */
