/*
 * RenderTypes.h
 *
 *  Created on: Jan 28, 2019
 *      Author: rookyma
 */

#ifndef SOURCE_CORE_RENDER_RENDERENUM_H_
#define SOURCE_CORE_RENDER_RENDERENUM_H_

#include <cstdint>

namespace Render
{
	enum class ImageType : uint32_t
	{
		IMAGE_TYPE_1D,
		IMAGE_TYPE_2D,
		IMAGE_TYPE_3D,
		IMAGE_TYPE_CUBE,
		IMAGE_TYPE_1D_ARRAY,
		IMAGE_TYPE_2D_ARRAY,
		IMAGE_TYPE_CUBE_ARRAY,
		IMAGE_TYPE_UNKNOWN = ~0u
	};

	enum class ShaderType : uint32_t
	{
		SHADER_TYPE_VERTEX,
		SHADER_TYPE_HULL,
		SHADER_TYPE_DOMAIN,
		SHADER_TYPE_GEOMETRY,
		SHADER_TYPE_FRAGMENT,
		SHADER_TYPE_COMPUTE,
		SHADER_TYPE_UNKNOWN = ~0U
	};

	enum class IndexType : uint32_t
	{
		INDEX_TYPE_U16,
		INDEX_TYPE_U32,
		INDEX_TYPE_UNKNOWN = ~0u
	};

	enum ShaderStage : uint32_t
	{
		SHADER_STAGE_VERTEX,
		SHADER_STAGE_HULL,
		SHADER_STAGE_DOMAIN,
		SHADER_STAGE_GEOMETRY,
		SHADER_STAGE_FRAGMENT,
		SHADER_STAGE_COMPUTE,
		SHADER_STAGE_ALL_GRAPHICS,
		SHADER_STAGE_UNKNOWN = ~0u
	};

}

#endif /* SOURCE_CORE_RENDER_RENDERENUM_H_ */
