/*
 * RenderTypes.h
 *
 *  Created on: Jan 28, 2019
 *      Author: rookyma
 */

#ifndef SOURCE_CORE_RENDER_RENDERTYPES_H_
#define SOURCE_CORE_RENDER_RENDERTYPES_H_

#include <cstdint>

namespace Render
{
	enum class ImageType : uint32_t
	{
		IMAGE_TYPE_1D,
		IMAGE_TYPE_2D,
		IMAGE_TYPE_3D,
		IMAGE_TYPE_CUBE,
		IMAGE_TYPE_1D_ARRAY,
		IMAGE_TYPE_2D_ARRAY,
		IMAGE_TYPE_CUBE_ARRAY,
		IMAGE_TYPE_UNKNOWN = ~0u
	};

	enum class IndexType : uint32_t
	{
		INDEX_TYPE_U16,
		INDEX_TYPE_U32,
		INDEX_TYPE_UNKNOWN = ~0u
	};

	enum class BufferUsageFlags : uint32_t
	{
		BUFFER_USAGE_COMMON = 0 << 0,
		BUFFER_USAGE_INDEX = 1 << 0,
		BUFFER_USAGE_VERTEX = 1 << 1,
		BUFFER_USAGE_UNIFORM = 1 << 2,
		BUFFER_USAGE_STORAGE = 1 << 3,
		BUFFER_USAGE_INDIRECT = 1 << 4,
		BUFFER_USAGE_UNIFORM_TEXEL = 1 << 5,
		BUFFER_USAGE_STORAGE_TEXEL = 1 << 6,
		BUFFER_USAGE_UNKNOWN = ~0u
	};

	enum class ImageUsageFlags : uint32_t
	{
		IMAGE_USAGE_COMMON = 0 << 0,
	    IMAGE_USAGE_SAMPLED = 1 << 0,
	    IMAGE_USAGE_STORAGE = 1 << 1,
	    IMAGE_USAGE_COLOR_ATTACHMENT = 1 << 2,
	    IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT = 1 << 3,
	    IMAGE_USAGE_TRANSIENT_ATTACHMENT = 1 << 4,
	    IMAGE_USAGE_INPUT_ATTACHMENT = 1 << 5,
	    IMAGE_USAGE_UNKNOWN = ~0u
	};

}

#endif /* SOURCE_CORE_RENDER_RENDERTYPES_H_ */
