/*
 * RenderSamplerState.h
 *
 *  Created on: Mar 27, 2019
 *      Author: rookyma
 */

#ifndef SOURCE_CORE_GHI_RENDERSAMPLERSTATE_H_
#define SOURCE_CORE_GHI_RENDERSAMPLERSTATE_H_

#include <cstdint>

namespace GHI
{

enum class FilterType : uint32_t
{
	FILTER_TYPE_NEAREST,
	FILTER_TYPE_LINEAR,
	FILTER_TYPE_CUBIC_IMG,
	FILTER_TYPE_UNKNOWN = ~0U
};

enum class MipmapMode : uint32_t
{
    MIPMAP_MODE_NEAREST,
    MIPMAP_MODE_LINEAR,
    MIPMAP_MODE_UNKNOWN = ~0U
};

enum class AddressMode : uint32_t
{
    ADDRESS_MODE_REPEAT,
    ADDRESS_MODE_MIRRORED_REPEAT,
    ADDRESS_MODE_CLAMP_TO_EDGE,
    ADDRESS_MODE_CLAMP_TO_BORDER,
    ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE,
    ADDRESS_MODE_UNKNOWN = ~0U
};

}

#endif /* SOURCE_CORE_GHI_RENDERSAMPLERSTATE_H_ */
